# Generated by Django 2.0.2 on 2018-06-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inner',
            new_name='Slider',
        ),
    ]
