# Generated by Django 2.0.2 on 2018-06-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0002_auto_20180621_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
    ]
