# Generated by Django 2.0.2 on 2018-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='icons',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
