# Generated by Django 2.0.2 on 2018-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0006_firstfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%y/%m/%D/'),
        ),
    ]
