# Generated by Django 2.1 on 2018-09-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0007_auto_20180625_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y/%m/%D/'),
        ),
    ]
